Models/Album.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Howl.Models
{
    public class Album
    {
        public int AlbumID { get; set; }
        public string CoverUrl { get; set; }
        public string AlbumTitle { get; set; }
        public string Artist { get; set; }
        public DateTime Year { get; set; }
        public Genre MusicGenre { get; set; }
        public enum Genre { ALTERNATIVE, BLUES, CLASSICAL, COMEDY, COUNTRY, DANCE, ELECTRONIC, RAP, ROCK}
    }
}

Pages/P/Admin.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Howl.Models;
using Howl.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Howl.Pages.P
{
    public class AdminModel : PageModel
    {
        private IUserService userService;
        private IAlbumService albumService;
        private IReviewService reviewService;
        public AdminModel(IUserService uService, IAlbumService aService, IReviewService rService)
        {
            userService = uService;
            albumService = aService;
            reviewService = rService;
        }
        [BindProperty]
        public IEnumerable<User> Users { get; set; }
        [BindProperty]
        public IEnumerable<Album> Albums { get; set; }
        [BindProperty]
        public IEnumerable<Review> Reviews { get; set; }

        public IActionResult OnGet()
        {
            /*string testname;
            HttpContext.Request.Cookies.TryGetValue("UserName", out testname);*/
            if (HttpContext.Request.Cookies["UserName"] != "Admin")
            {
                return RedirectToPage("../Index");
            }
            Users = userService.GetUsers();
            Albums = albumService.GetAlbums();
            Reviews = reviewService.GetReviews();
            return Page();
        }
    }
}

Pages/P/Album.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Howl.Services;
using Howl.Models;

namespace Howl.Pages.P
{
    public class AlbumModel : PageModel
    {
        private IAlbumService _albumService;
        private IReviewService _reviewService;

        public AlbumModel(IAlbumService albumService, IReviewService reviewService)
        {
            _albumService = albumService;
            _reviewService = reviewService;
        }

        [BindProperty]
        public IEnumerable<Review> Reviews { get; set; }
        [BindProperty]
        public double Rating { get; set; }
        [BindProperty]
        public Album Album { get; set; }

        public void OnGet(int id)
        {
            Album = _albumService.GetAlbumByID(id);
            Reviews = _reviewService.GetReviews().Where(r  =>  r.Album.AlbumID  ==  id);
            //List<Review> test = new List<Review>();
            //test = Reviews.Where(r => r.ReviewID == id);
            if (Reviews.Count() !=  0)
            {
                Rating = Reviews.Average(r => r.StarRating);
            }
        }
    }
}

Pages/P/AllAlbums.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Howl.Models;
using Howl.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Howl.Pages.P
{
    public class AllAlbumsModel : PageModel
    {
        private IAlbumService _albumService;
        public AllAlbumsModel(IAlbumService albumService)
        {
            _albumService = albumService;
        }

        [BindProperty]
        public IEnumerable<Album> Albums { get; set; }
        [BindProperty(SupportsGet =true)]
        public Album.Genre? Genre { get; set; }
        public IActionResult OnGet(Album.Genre? genre)
        {
            Albums = _albumService.GetAlbums();
            if (Genre != null)
            {
                Albums = Albums.Where(a => a.MusicGenre == Genre);
            }
            return Page();
        }

        /*public IActionResult OnPost()
        {
            return RedirectToPage("AllAlbums", new { genre = Genre });
        }*/
    }
}

Pages/P/AllReviews.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Howl.Models;
using Howl.Services;

namespace Howl.Pages.P
{
    public class AllReviewsModel : PageModel
    {
        private IAlbumService _albumService;
        private IReviewService _reviewService;

        public AllReviewsModel(IAlbumService albumService, IReviewService reviewService)
        {
            _albumService = albumService;
            _reviewService = reviewService;
        }

        [BindProperty]
        public List<Review> Reviews { get; set; }

        public IActionResult OnGet()
        {
            Reviews = _reviewService.GetReviews();
            foreach (Review item in Reviews)
            {
                item.Album = _albumService.GetAlbumByID(item.Album.AlbumID);
            }
            Reviews = Reviews.OrderByDescending(r => r.PublishDateTime).ToList();
            return Page();
        }
    }
}

Pages/P/HomePage.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Howl.Models;
using Howl.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Howl.Pages
{
    public class HomePageModel : PageModel
    {
        private IReviewService _reviewService;
        private IUserService _userService;
        private IAlbumService _albumService;
        public HomePageModel(IReviewService reviewService, IUserService userService, IAlbumService albumService)
        {
            _reviewService = reviewService;
            _userService = userService;
            _albumService = albumService;
        }
        [BindProperty]
        public List<Review> Reviews { get; set; }
        [BindProperty]
        public List<Review> FollowerReview { get; set; }
        [BindProperty]
        public List<User> Followers { get; set; }
        [BindProperty]
        public User User1 { get; set; } = new User();
        [BindProperty]
        public User fu { get; set; } = new User();
        [BindProperty]
        public Review likedislike { get; set; }

        public IActionResult OnGet()
        {
            //bool test = HttpContext.Request.Cookies.ContainsKey("UserName");
            string testname;
            HttpContext.Request.Cookies.TryGetValue("UserName",out testname);
            User1.Username = testname;
            //  Get newest reviews
            Reviews = _reviewService.GetReviews();
            foreach (Review item in Reviews)
            {
                item.Album = _albumService.GetAlbumByID(item.Album.AlbumID);
            }
            Reviews = Reviews.OrderByDescending(r => r.PublishDateTime).ToList();

            //  Get followers reviews
            Followers = _reviewService.GetFollowers(User1);
            FollowerReview = _reviewService.GetReviewsFromUserList(Followers).OrderByDescending(r=>r.PublishDateTime).ToList();
            foreach (Review item in FollowerReview)
            {
                item.Album = _albumService.GetAlbumByID(item.Album.AlbumID);
            }
            return Page();
        }

        public IActionResult OnPostFollow()
        {
            _userService.FollowUser(User1, fu);
            return RedirectToPage("HomePage");
        }

        public IActionResult OnPostUnfollow()
        {
            _userService.UnFollowUser(User1, fu);
            return RedirectToPage("HomePage");
        }

        public IActionResult OnPostLike()
        {
            Review review = _reviewService.GetReviewById(likedislike);
            _reviewService.Like(review);
            return RedirectToPage("HomePage");
        }

        public IActionResult OnPostDislike()
        {
            Review review = _reviewService.GetReviewById(likedislike);
            _reviewService.Dislike(review);
            return RedirectToPage("HomePage");
        }

    }
}

Pages/P/Profile.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Howl.Services;
using Howl.Models;

namespace Howl.Pages.P
{
    public class ProfileModel : PageModel
    {
        private IReviewService _reviewService;
        private IUserService _userService;

        public ProfileModel(IReviewService reviewService, IUserService userService)
        {
            _reviewService = reviewService;
            _userService = userService;
        }

        [BindProperty]
        public IEnumerable<Review> Reviews { get; set; }
        [BindProperty]
        public User User { get; set; }
        [BindProperty]
        public int FollowerCount { get; set; }
        [BindProperty]
        public int FollowedCount { get; set; }
        [BindProperty]
        public int ReviewsWritten { get; set; }
        [BindProperty]
        public Review Review { get; set; }

        public void OnGet()
        {
            string testname;
            HttpContext.Request.Cookies.TryGetValue("UserName", out testname);
            //User1.Username = testname;
            User = _userService.GetUserById(testname);
            FollowerCount = _reviewService.GetFollowers().Where(u => u.Username == testname).Count();
            FollowedCount = _reviewService.GetFollowers(User).Count();
            Reviews = _reviewService.GetReviews().Where(r => r.User.Username == testname);

            if (Reviews.Count() > 0)
            {
                ReviewsWritten = Reviews.Count();
            }
            else
            {
                ReviewsWritten = 0;
            }
        }

        public IActionResult OnPostDelete()
        {
            _reviewService.DeleteReview(Review.ReviewID);
            return RedirectToPage("Profile");
        }

        public IActionResult OnPostLogout()
        {
            HttpContext.Response.Cookies.Delete("UserName");
            return RedirectToPage("AllReviews");
        }
    }
}

Pages/P/SearchResult.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Howl.Models;
using Howl.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Howl.Pages.P
{
    public class SearchResultModel : PageModel
    {
        private IAlbumService service;
        public SearchResultModel(IAlbumService albumService)
        {
            service = albumService;
        }

        [BindProperty(SupportsGet = true)]
        public string SearchTerm { get; set; }
        [BindProperty]
        public IEnumerable<Album> Albums { get; set; }
        public void OnGet()
        {
            Albums = service.GetAlbums();
            if (!String.IsNullOrEmpty(SearchTerm))
            {
                Albums = Albums.Where(a => a.AlbumTitle.ToLower().Contains(SearchTerm.ToLower()));
            }
        }
    }
}

Pages/P/WriteReview.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Howl.Services;
using Howl.Models;

namespace Howl.Pages
{
    public class WriteReviewModel : PageModel
    {
        /*public List<Review> reviews { get; set; }*/
        private IReviewService _reviewService;
        private IAlbumService _albumService;

        [BindProperty]
        public Review Review { get; set; }
        [BindProperty]
        public int albumid { get; set; }
        [BindProperty]
        public int StarRating { get; set; }
        public WriteReviewModel(IReviewService reviewService, IAlbumService albumService)
        {
            _reviewService = reviewService;
            _albumService = albumService;
        }
        
        public IActionResult OnGet(int id)
        {
            Review = new Review();
            Review.StarRating = 0;
            albumid = id;
            Review.Album = _albumService.GetAlbumByID(id);
            //Review.User.Username = "testerman";
            //Review.Album.AlbumID = 666;
            /*reviews = ReviewService.GetReviews();*/
            //Review.User = _reviewService.GetUser(Review);
            //Review.Album = _reviewService.GetAlbum(Review);
            return Page();
        }

        public IActionResult OnPost()
        {
            Review.User = new User();
            string testname;
            HttpContext.Request.Cookies.TryGetValue("UserName", out testname);
            Review.User.Username = testname;
            Review.Album = new Album();
            Review.Album.AlbumID = albumid;
            Review.StarRating = StarRating;
            //Review.PublishDateTime = DateTime.Now;
            _reviewService.AddReview(Review);
            return RedirectToPage("HomePage");
        }
    }
}

Pages/P/Admin.cshtml
@page
@model Howl.Pages.P.AdminModel
@{
}
<h1>Admin Page</h1>

<button class="btn btn-primary" onclick="$('#Album').toggle()">See Albums</button>
<button class="btn btn-primary" onclick="$('#Review').toggle()">See Reviews</button>
<button class="btn btn-primary" onclick="$('#User').toggle()">See Users</button>

<div style="display:none;" id="Album">
    <h2>See all albums</h2>
    <table class="table table-striped">
        <thead>
            <tr>
                <th>Album ID</th>
                <th>Album Title</th>
            </tr>
        </thead>
        <tbody>
            @if (Model.Albums.Count() != 0)
            {
                @foreach (var a in Model.Albums)
                {
                    <tr>
                        <td>@a.AlbumID</td>
                        <td>@a.AlbumTitle</td>
                    </tr>
                }
            }
        </tbody>
    </table>
</div>
<div style="display:none;" id="Review">
    <h2>See all reviews</h2>
    <table class="table table-striped">
        <thead>
            <tr>
                <th>Review ID</th>
                <th>Review Title</th>
                <th>Review User</th>
            </tr>
        </thead>
        <tbody>
            @if (Model.Reviews.Count() != 0)
            {
                @foreach (var r in Model.Reviews)
                {
                    <tr>
                        <td>@r.ReviewID</td>
                        <td>@r.ReviewTitle</td>
                        <td>@r.User.Username</td>
                    </tr>
                }
            }
        </tbody>
    </table>
</div>
<div style="display:none;" id="User">
    <h2>See all users</h2>
    <table class="table table-striped">
        <thead>
            <tr>
                <th>Username</th>
                <th>Password</th>
            </tr>
        </thead>
        <tbody>
            @if (Model.Users.Count() != 0)
            {
                @foreach (var u in Model.Users)
                {
                    <tr>
                        <td>@u.Username</td>
                        <td>@u.Password</td>
                    </tr>
                }
            }
        </tbody>
    </table>
</div>

Pages/P/HomePage.cshtml
@page
@model Howl.Pages.HomePageModel
@{
}
<div class="row">
    <div class="col-6 d-inline">
            <button class="btn btn-secondary btn-sm float-right" onclick="$('#fl').toggle()">See Followers</button>
            <h3>Follower Review</h3>

        <div id="fl" style="display:none;">
            <ul>
                @if (Model.Followers.Count != 0)
                {
                    @foreach (var f in Model.Followers)
                    {
                        <li>@f.Username</li>
                    }
                }
            </ul>
        </div>
        @if (Model.Reviews.Count != 0)
        {
            @foreach (var rv in Model.FollowerReview)
            {
                <div class="card">
                    <div class="card-header">
                        <h5 class="card-title d-inline">@rv.Album.AlbumTitle</h5>
                        <div>
                            @for (int i = 0; i < rv.StarRating; i++)
                            {
                                <i class="fa fa-star" aria-hidden="true"></i>
                            }
                        </div>
                    </div>
                    <div class="card-body">
                        <img class="float-right" height="150" width="150" src="@rv.Album.CoverUrl" />
                        <p><strong>@rv.ReviewTitle</strong></p>
                        <p class="card-text text-light">@rv.ReviewText</p>
                    </div>
                    <div>
                        <form class="d-inline" method="post" asp-page-handler="Like">
                            <input type="hidden" asp-for="@Model.likedislike.ReviewID" value="@rv.ReviewID" />
                            <button class="btn btn-success col-2 d-inline"><i class="fa fa-thumbs-o-up"></i></button>
                        </form>
                        @*<p class="text-success d-inline">@rv.Like</p>*@
                        <form class="d-inline" method="post" asp-page-handler="Dislike">
                            <input type="hidden" asp-for="@Model.likedislike.ReviewID" value="@rv.ReviewID" />
                            <button class="btn btn-danger col-2 d-inline"><i class="fa fa-thumbs-o-down"></i></button>
                        </form>
                        @*<p class="text-danger d-inline">@rv.Dislike</p>*@
                        <div class="d-inline">
                            <p class="card-text d-inline col"><em>@rv.User.Username</em></p>
                            <p class=" card-text d-inline float-right mr-1">@rv.PublishDateTime.ToString("dd/MM/yyyy")</p>
                        </div>
                    </div>
                </div>
                <div class="d-flex">
                    <p class="text-light">Review rating:</p>
                @if (rv.Like == 0 && rv.Dislike == 0)
                {
                        <p class="text-light" style="margin-left: 1em">Undecided</p>
                }
                else if (rv.Like != 0 || rv.Dislike != 0)
                {
                    if (rv.Like > rv.Dislike)
                    {
                        if (rv.Like > rv.Dislike + 10)
                        {
                                    <div class="d-flex">
                                        <p class="text-success" style="margin-left: 1em">Overwhelmingly positive</p>
                                        <p class="text-light" style="margin-left: 1em"> (@(rv.Like += rv.Dislike))</p>
                                    </div>
                        }
                        else if (rv.Like > rv.Dislike + 5)
                        {
                                    <div class="d-flex">
                                        <p class="text-success" style="margin-left: 1em">Very positive</p>
                                        <p class="text-light" style="margin-left: 1em"> (@(rv.Like += rv.Dislike))</p>
                                    </div>
                        }
                        else
                        {
                                    <div class="d-flex">
                                        <p class="text-success" style="margin-left: 1em">Mostly positive</p>
                                        <p class="text-light" style="margin-left: 1em"> (@(rv.Like += rv.Dislike))</p>
                                    </div>
                        }
                    }
                    else if (rv.Like == rv.Dislike)
                    {
                                <div class="d-flex">
                                     <p class="text-warning" style="margin-left: 1em">Mixed</p>
                                     <p class="text-light" style="margin-left: 1em"> (@(rv.Like += rv.Dislike))</p>
                                </div>
                    }
                    else
                    {
                        if (rv.Like < rv.Dislike - 5)
                        {
                                    <div class="d-flex">
                                        <p class="text-danger" style="margin-left: 1em">Very negative</p>
                                        <p class="text-light" style="margin-left: 1em"> (@(rv.Like += rv.Dislike))</p>
                                    </div>
                        }
                        else
                        {
                                    <div class="d-flex">
                                        <p class="text-danger" style="margin-left: 1em">Mostly negative</p>
                                        <p class="text-light" style="margin-left: 1em"> (@(rv.Like += rv.Dislike))</p>
                                    </div>
                            }
                        }
                    }
                    
        </div>
            }
        }
    </div>
    <div class="col-6 d-inline">
        <h3>Newest reviews</h3>
        @if (Model.Reviews.Count != 0)
        {
            @foreach (var rv in Model.Reviews)
            {
                <div class="card">
                    <div class="card-header">
                        <h5 class="card-title d-inline">@rv.Album.AlbumTitle</h5>
                        <div>
                            @for (int i = 0; i < rv.StarRating; i++)
                            {
                                <i class="fa fa-star" aria-hidden="true"></i>
                            }
                        </div>
                    </div>
                    <div class="card-body">
                        <img class="float-right" height="150" width="150" src="@rv.Album.CoverUrl" />
                        <p><strong>@rv.ReviewTitle</strong></p>
                        <p class="card-text text-light">@rv.ReviewText</p>
                    </div>
                    <div>
                        <form class="d-inline" method="post" asp-page-handler="Like">
                            <input type="hidden" asp-for="@Model.likedislike.ReviewID" value="@rv.ReviewID" />
                            <button class="btn btn-success col-2 d-inline"><i class="fa fa-thumbs-o-up"></i></button>
                        </form>
                        @*<p class="text-success d-inline">@rv.Like</p>*@
                        <form class="d-inline" method="post" asp-page-handler="Dislike">
                            <input type="hidden" asp-for="@Model.likedislike.ReviewID" value="@rv.ReviewID" />
                            <button class="btn btn-danger col-2 d-inline"><i class="fa fa-thumbs-o-down"></i></button>
                        </form>
                        @*<p class="text-danger d-inline">@rv.Dislike</p>*@
                        <div class="d-inline">
                            
                            @if (!Model.Followers.Contains(Model.Followers.Find(u => u.Username == rv.User.Username)))
                            {
                                <form class="d-inline" method="post" asp-page-handler="follow">
                                    <input type="hidden" asp-for="@Model.User1.Username" value="@Model.User1.Username" />
                                    <input type="hidden" asp-for="@Model.fu.Username" value="@rv.User.Username" />

                                    <input type="submit" class="btn btn-primary btn-sm" value="Follow" />
                                </form>
                            }
                            else
                            {
                        <form class="d-inline" method="post" asp-page-handler="unfollow">
                            <input type="hidden" asp-for="@Model.User1.Username" value="@Model.User1.Username" />
                            <input type="hidden" asp-for="@Model.fu.Username" value="@rv.User.Username" />
                            <input type="submit" class="btn btn-outline-primary btn-sm" value="Unfollow" />
                        </form>
                            }
                            <p class="card-text d-inline col mr-1"><em>@rv.User.Username</em></p>
                            <p class=" card-text d-inline float-right mr-2">@rv.PublishDateTime.ToString("dd/MM/yyyy")</p>
                        </div>
                    </div>
                </div>
                <div class="d-flex">
                    <p class="text-muted">Review rating:</p>
                    @if (rv.Like == 0 && rv.Dislike == 0)
                    {
                        <p class="text-muted" style="margin-left: 1em">Undecided</p>
                        }
                        else if (rv.Like != 0 || rv.Dislike != 0)
                        {
                            if (rv.Like > rv.Dislike)
                            {
                                if (rv.Like > rv.Dislike + 10)
                                {
                                    <div class="d-flex">
                                        <p class="text-success" style="margin-left: 1em">Overwhelmingly positive</p>
                                        <p class="text-muted" style="margin-left: 1em"> (@(rv.Like += rv.Dislike))</p>
                                    </div>
                                }
                                else if (rv.Like > rv.Dislike + 5)
                                {
                                    <div class="d-flex">
                                        <p class="text-success" style="margin-left: 1em">Very positive</p>
                                        <p class="text-muted" style="margin-left: 1em"> (@(rv.Like += rv.Dislike))</p>
                                    </div>
                                }
                                else
                                {
                                    <div class="d-flex">

                                        <p class="text-success" style="margin-left: 1em"> Mostly positive </p>

                                        <p class="text-muted" style="margin-left: 1em"> (@(rv.Like += rv.Dislike))</p>

                                    </div>
                                }
                            }
                            else if (rv.Like == rv.Dislike)
                            {
                                <div class="d-flex">

                                    <p class="text-warning" style="margin-left: 1em"> Mixed </p>

                                    <p class="text-muted" style="margin-left: 1em"> (@(rv.Like += rv.Dislike))</p>

                                </div>
                            }
                            else
                            {
                                if (rv.Like < rv.Dislike - 5)
                                {
                                    <div class="d-flex">

                                        <p class="text-danger" style="margin-left: 1em"> Very negative </p>

                                        <p class="text-muted" style="margin-left: 1em"> (@(rv.Like += rv.Dislike))</p>

                                    </div>
                                }
                                else
                                {
                                    <div class="d-flex">

                                        <p class="text-danger" style="margin-left: 1em"> Mostly negative </p>

                                        <p class="text-muted" style="margin-left: 1em"> (@(rv.Like += rv.Dislike))</p>

                                    </div>
                                }
                            }
                        }
                        

                    </div>
            }
        }
    </div>
</div>

Pages/P/Profile.cshtml
@page
@model Howl.Pages.P.ProfileModel
@{
}
<div class="bg-dark float-left">
    <img height="300" width="300" src="https://upload.wikimedia.org/wikipedia/commons/7/7c/Profile_avatar_placeholder_large.png" />
    <div class="card">
        <div class="card-body">
            <p class="card-text float-left text-light d-inline">Username:</p>
            <p class="card-text float-right text-info d-inline">@Model.User.Username</p>
        </div>
        <div class="card-body">
            <p class="card-text float-left text-light d-inline">Followers:</p>
            <p class="card-text float-right text-info d-inline">@Model.FollowerCount</p>
        </div>
        <div class="card-body">
            <p class="card-text float-left text-light d-inline">Following:</p>
            <p class="card-text float-right text-info d-inline">@Model.FollowedCount</p>
        </div>
        <div class="card-body">
            <p class="card-text float-left text-light d-inline">Written reviews:</p>
            <p class="card-text float-right text-info d-inline">@Model.ReviewsWritten</p>
        </div>
        <div class="card-footer">
            <form method="post" asp-page-handler="Logout">
                <input class="btn btn-danger" type="submit" value="Logout" />
            </form>
        </div>
    </div>
</div>
<div class="float-right w-50">
    <h3 class="text-light">Reviews written by @Model.User.Username</h3>
    @if (Model.Reviews.Count() != 0)
    {
        @foreach (var rv in Model.Reviews)
        {
<div class="bg-dark w-100 card mb-5">
    <div class="card-header">
        <h5 class="card-title d-inline">@rv.Album.AlbumTitle</h5>
        <p class="card-text d-inline"><strong>@rv.ReviewTitle</strong></p>
        <div class="d-inline">
            @for (int i = 0; i < rv.StarRating; i++)
            {
                <i class="fa fa-star" aria-hidden="true"></i>
            }
        </div>
    </div>
    <div class="card-body">
        <p class="card-text text-light">@rv.ReviewText</p>
    </div>
    <div>
        <form class="d-inline ml-3" method="post" asp-page-handler="Delete">
            <input type="hidden" asp-for="@Model.Review.ReviewID" value="@rv.ReviewID" />
            <button class="btn btn-danger col-2 d-inline"><i class="fa fa-times"></i> Delete</button>
        </form>
    </div>
    <div>
        <div class="d-inline">
            @*<p class="card-text text-white d-inline col mr-1"><em>@rv.User.Username</em></p>*@
            <p class=" card-text text-info d-inline float-right mr-2">@rv.PublishDateTime.ToString("dd/MM/yyyy")</p>
        </div>
    </div>
</div>
        }
    }
</div>

